appveyor.yml
functions/disk/Initialize-PSDCVhdDisk.ps1
functions/disk/New-PSDCVhdDisk.ps1
functions/image/New-PSDCImage.ps1
readme.md
tests/appveyor/preparation.ps1
tests/constants.ps1
tests/functions/Initialize-PSDCVhdDisk.Tests.ps1
tests/functions/New-PSDCImage.Tests.ps1
tests/functions/New-PSDCVhdDisk.Tests.ps1
tests/pester.ps1

There was a problem with the creation of an image when the path couldn't be reached. This should now be solved.

Fix vhd path error fixes #18

---

appveyor.yml
tests/appveyor/preparation.ps1
tests/constants.ps1
tests/functions/New-PSDCImage.Tests.ps1

Added development branch to appveyor file

---

PSDatabaseClone/internal/scripts/preimport.ps1

Added Windows server 2008 r2 as a supported version

Added supported versions fixes #27

---

PSDatabaseClone/functions/support/Set-PSDCConfiguration.ps1

Added an extra check and try/catch block to catch any errors

Added extra check fixes #29

---

PSDatabaseClone/functions/clone/New-PSDCClone.ps1
PSDatabaseClone/functions/clone/Remove-PSDCClone.ps1

https://github.com/sqlcollaborative/PSDatabaseClone/issues/44

Bugfix for issue 44

---

PSDatabaseClone/functions/support/Set-PSDCConfiguration.ps1

This PR fixes the computer name issue

Computername fix

---

PSDatabaseClone/functions/clone/New-PSDCClone.ps1
PSDatabaseClone/functions/image/New-PSDCImage.ps1

Filter the partitions for the first one which is not Reserved, and then select the first partition.

Find first non-reserved partition

---

PSDatabaseClone/functions/image/Remove-PSDCImage.ps1

New pull request for just this feature for removing unused images.

Add ability to remove unused images

---

PSDatabaseClone/functions/clone/Remove-PSDCClone.ps1

Changed the variable

---

functions/image/New-DcnImage.ps1
tests/functions/image/New-DcnImage.Tests.ps1

Added the feature. It's now possible to point to a specific backup file. It's limited to one database though. You cannot enter multiple databases in the -Database parameter

Added feature to restore from bak file

---

functions/clone/Invoke-DcnRepairClone.ps1

Removed command and made it to server object
Added check for already connected disk
Added check for existing database
Fixed repair to use offline and online methods
Fixed messages
Fixes #89

Fixed Invoke-DcnRepairClone command

---

dbaclone.psd1
functions/clone/Get-DcnClone.ps1
functions/clone/Invoke-DcnRepairClone.ps1
functions/host/Get-DcnHost.ps1
internal/scripts/postimport.ps1
internal/tepp/assignment.ps1
internal/tepp/clones.tepp.ps1
internal/tepp/example.tepp.ps1
internal/tepp/images.tepp.ps1
tests/functions/clone/Get-DcnClone.Tests.ps1
tests/functions/host/Get-DcnHost.Tests.ps1

Added command to get all the hosts that have clones
Fixed creation of PS-Drive
Implemented TEPP to make it easier to run commands

New command and TEPP implementation

---

functions/clone/New-DcnClone.ps1
functions/support/Set-DcnPermission.ps1

Added error handling in several commands
Fixed destination in New-DcnClone
Fixed instance in New-DcnClone
Moved checks around to make them easier to read and more logical in processing

Small fixes

---

functions/support/Set-DcnConfiguration.ps1

Fix the path to the sql file when using the SQL Server configuration

Fixed the path to the database.sql file

---

functions/support/Set-DcnConfiguration.ps1
internal/resources/database/database.sql

There were some errors in the `database.sql` file which are now solved.
Fixed #123

Fix error in database creation

---

functions/image/New-DcnImage.ps1
internal/scripts/postimport.ps1

Fixed the issues raised in issue #130.
Added logic to check if the command should be run on local or remote. 
Also moved the permissions logic to be contained with the localhost condition.

Resolved issue #130

---

functions/clone/New-DcnClone.ps1

This change fixes an error when cloning an image that was created by a different user.

Clone perm fix

---

functions/image/New-DcnImage.ps1

Added feature to execute TSQL after the restore #126
It's now possible to execute both TSQL command and complete TSQL files using the parameters ExecuteSQLCommand and ExecuteSQLFile

Execute SQL code Pre Image creation

---

internal/functions/tests/Test-DncVersion.ps1
internal/scripts/postimport.ps1

After the module is loaded a test will be performed to test if the users is using the latest version of the module.
Refers to #139

Test the version of the module 

---

functions/support/Test-DcnModule.ps1

Added windows 11 insiders edition as a supported windows version

Added windows 11 insiders edition

---

functions/image/New-DcnImage.ps1

Changing SQL instance to use the destination instead of source.

---

functions/image/New-DcnImage.ps1

Messed up on this, Should be `$DestinationSqlInstance` not `$DestinationSqlCredential`.

Correct variable name, should be instance not credential.

---

internal/scripts/postimport.ps1

add parenthesis for psdrive existence check

---

internal/scripts/postimport.ps1

Sorry, missed including this in #160, but basically the same issue.

postimport.ps1: add parenthesis for informationstore check

---

functions/support/Set-DcnConfiguration.ps1

Fixes #173 by using the more robust New-DbaDatabase versus inline TSQL.

Set-DcnConfiguration: create config database as 'simple' by default

---

functions/clone/Remove-DcnClone.ps1

Implement Issue #175

---

functions/image/New-DcnImage.ps1

New-DcnImage: Get backup time from restore if needed

---

functions/clone/New-DcnClone.ps1

New-DcnClone: fix vhd typo

---

functions/clone/New-DcnClone.ps1

New-DcnClone: don't strip trailing slash from root dirs

---

functions/clone/Remove-DcnClone.ps1

Remove-DcnClone: add recurse for dir removal

---

functions/clone/New-DcnClone.ps1

New-DcnClone: Cleanup diskpart.txt file

---

functions/clone/New-DcnClone.ps1
functions/clone/Remove-DcnClone.ps1
functions/image/New-DcnImage.ps1

Changes made in this PR:
- Fix removing diskpart.txt after actions
- Fix showing clone vhd name instead of empty var
- Removed clones with recurse
Thank you all who worked on these changes!

Small changes

---

functions/clone/Invoke-DcnRepairClone.ps1

Invoke-DcnRepairClone: check for psdrive before creating
