PSDatabaseClone/functions/clone/New-PSDCClone.ps1

Memory-optimized files in SQL are actually folders with a .mdf extension instead of files.  A stricter search could look for only .mdf and .ldf files/folders, but wouldn't be able to take advantage of the performance of the -Filter option.

Include memory-optimized files

---

PSDatabaseClone/functions/image/Remove-PSDCImage.ps1

When using the Remove-PSDCImage function, the JSON database gets cleared because the $newImageData variable is never set.

Fix bug where JSON database cleared

---

PSDatabaseClone/functions/image/New-PSDCImage.ps1

When no full backup was assigned the command could fail if it couldn't find the backup file.
The command now checks the availability of the full backup

Fix Image Backup error

---

internal/scripts/preimport.ps1

This will ensure any additional whitespace is removed, which can cause issues when looking up the edition in the supported array

Trim the windows edition string before lookup

---

functions/image/New-PSDCImage.ps1

Changed the way the command checks for the network and local path.
No longer will the command check for the local path because it's derived from the UNC path anyways

Changed check to not error out later on

---

functions/support/Set-PSDCConfiguration.ps1

This should fix #72
`$InformationStore` was recieving a default value of `'File'`. Because of this, this line wasn't functioning correctly:
```
if ($InputPrompt -or (-not $InformationStore) -and (-not $SqlInstance -and -not $SqlCredential -and -not $Credential -and -not $Database)) {
```
The above condition determines if we enter into the interactive prompt. We do so if `$InputPrompt` is true, or if we don't have any values for `$InformationStore`. Since we don't provide either, but `$InformationStore` was being defaulted, the script never entered into the conditional block.
Additionally, there was an issue of `$Path` variable being operated on when there was not path variable (for example, database store). I made a quick fix just to make sure we have `$Path` before using it. That being …

Removes default value for $InformationStore & check $Path variable

---

functions/disk/Initialize-PSDCVhdDisk.ps1

This is due to Get-Disk not having Location for the mounted files for some reason.
This resolves parts of #70

Get the disk image by path, and use the number to get the disk.

---

functions/clone/New-PSDCClone.ps1
functions/clone/Remove-PSDCClone.ps1
functions/image/New-PSDCImage.ps1

For the use with docker the database should not be mounted after the clone has been made.
This way the user can reference the shared folder and let the docker sql server open the database files
A lot of extra checks were added and the possibility for not having an instance name in the clone record was implemented.

Docker support

---

functions/clone/New-PSDCClone.ps1
functions/disk/Initialize-PSDCVhdDisk.ps1

Resolves #82.
Was running into the same issue with the clone command as I did with the image command, in that `Get-Disk` did not provide `Location` property for mounted disks. 
---
Update: I reverted this as it didn't work as I expected. But might be useful to keep these data around as it is something that would need to be fixed 😄 
Additionally, I fixed the New Image command to bypass the Location parameter during the mounted check.
@sanderstad You might want to look at this bit of code in the New-PSDCClone function:
```
else {
$command = [ScriptBlock]::Create("Mount-DiskImage -ImagePath `"$($clonePath)`"")
$null = Invoke-PSFCommand -ComputerName $computer -ScriptBlock $command -Credential $Credential
$command = [ScriptBlock]::Create("Get-Vhd -Path `"$($clonePath)`"")
$disk = …
```

Fixes clone creation command - Get-Disk doesn't retun Location parameter

---

internal/functions/tests/Test-DcnConfiguration.ps1

The references for the config testing command where pointing to the old name of the module.
This has been fixed.
Fixes #101

Renamed PSDatabaseClone to dbaclone

---

functions/clone/New-DcnClone.ps1
functions/clone/Remove-DcnClone.ps1
functions/image/Remove-DcnImage.ps1
functions/support/Test-DcnModule.ps1

Removed `Credential` parameter from the Test-Path command as it threw an error because it is an invalid parameter.
I added a check to ensure the Clone file has been deleted before removing the database record. The check has been added as there have been instances in testing where the database record has been deleted but the clone still exists which then prevents the image from being deleted as it is in use.
Changed the logic [here](#diff-8000bdb9c952c1e41dbaeb5ccf41af418bda024020807c5bb7f139c44243b63eL232-R231) because when `Get-DcnClone` returns 1 clone the `$Result.Count` is null.
I also added a check to ensure the Image file has been deleted before removing the database record. This has been added as there have been instances where the image still exists but the database records have …

Fixed Clone 

---

functions/clone/New-DcnClone.ps1

Hi @sanderstad,
Could I get this fix merged into Development and Master as soon as possible, please? Currently unable to clone new images if there are multiple images for a given database.

Fixed issue where LatestImage flag wouldn't get the latest Image.

---

functions/clone/New-DcnClone.ps1

same as the disk mount command above it

New-DcnClone: fix $clonepath escaping

---

functions/clone/New-DcnClone.ps1

If you use then New-DcnClone from remote machine, Join-PSFPath not work when $server.DefaultFile contains volume that non exist on local PC.
I have convert Join-PSFPath to [System.IO.Path]::Combine when New-DcnClone initialize the destination folder.

Fix new clone (volume not found) from remote, when no destination folder is specified

---

functions/clone/Remove-DcnClone.ps1

When use Remove-DcnClone from remote, fails because Test-Path is execute on local machine and not remotely.
```
if ($PSCmdlet.ShouldProcess($item.CloneLocation, "Dismounting the vhd")) {
try {
if (Test-Path -Path $item.CloneLocation) {
if ($computer.IsLocalhost) {
Write-PSFMessage -Message "Dismounting disk '$($item.CloneLocation)' from $($item.HostName)" -Level Verbose
$null = Dismount-DiskImage -ImagePath $item.CloneLocation
}
else {
$command = [ScriptBlock]::Create("Test-Path -Path '$($item.CloneLocation)'")
.....
```

Fix dismount vhd when use Remove-DcnClone from remote

---

functions/image/New-DcnImage.ps1

Fixes #170 - Invoke-DbaQuery only accepts `Database` as a param and not `DatabaseName`

use database as param for invoke-dbaquery

---

functions/support/Test-DcnModule.ps1

We migrated to Windows 2022 for our Image build server and started getting the unsupported windows version warning so added the 2022 versions.

Adding 2022 to supported windows version .

---

functions/clone/New-DcnClone.ps1

Closes #176 
Closes #146
Please let me know if there's any thoughts here. It is my understanding that $ParentVHD and ($Database, $LatestImage) are mutually exclusive. However, the codebase requires $Database to be set, so when using $ParentVHD it wont actually work (since there are no databases set). This fix basically looks up the database name if supplied a ParentVHD
I also added a new parameter, $ImageID, to be able to create a clone based on an image ID.
Also, I'm not sure what utility $LatestImage has. The code looks like this:
```
foreach ($db in $Database) {
if (-not $ParentVhd) {
if ($LatestImage) {
$result = Get-DcnImage -Database $db | Sort-Object -Descending CreatedOn | Select-Object -First 1
}
if ($null -eq $result) {
Stop-PSFFunction -Message "No image could be found for …
```

Fix for Issue 176

---

functions/support/Test-DcnRemoting.ps1

Change incorrect references to HostName to ComputerName within the documentation/output.

Test-DcnRemoting: fix hostname -> computername references

---

functions/clone/New-DcnClone.ps1

The error message is referencing a null variable, use $clonePath instead.

New-DcnClone: fix error using empty var

---

functions/image/New-DcnImage.ps1

Fixes #172. 
May want to wait until https://github.com/dataplat/dbatools/pull/8330 is landed though, to make sure the proper size is getting recorded.

New-DcnClone: Set actual image size when using backup file source

---

functions/support/Test-DcnModule.ps1

Windows 10 Pro - once hybrid-joined or azure-joined gets changed to 'Microsoft Windows 10 Pro Education'

Add Microsoft Windows 10 Pro Education to supported version
